name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Sutil/snk@v01.00.02
        id: snake-gif
        with:
          github_user_name: VictorPera
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: Sutil/snk@v01.00.02
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
